Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/*.rb'
    - 'app/helpers/*.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'db/schema.rb'
    - 'spec/**/*'
    - 'config/initializers/simple_form_bootstrap.rb'
