Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'app/models/user.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'config/routes.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/*.rb'
    - 'app/helpers/*.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/SymbolArray:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/rooms_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'db/schema.rb'
    - 'spec/**/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/environments/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
