language: ruby

sudo: false

cache: bundler

addons:
  postgresql: 9.3

before_script:
  - 'RAILS_ENV=test bundle exec rake db:create --trace'

script:
  - bundle exec rspec

notifications:
  email: false
